/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "sa-east-1:9428d48b-10fe-446f-be57-bcbf6fa5a55a",
    "aws_cognito_region": "sa-east-1",
    "aws_user_pools_id": "us-east-1_cQMFBCYpo",
    "aws_user_pools_web_client_id": "3apm1s06kq3efigsoh0md2gl1d",
    "oauth": {},
    "aws_user_files_s3_bucket": "repoprovasbucket04859-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export { awsconfig };
